# Generated by Django 2.1.3 on 2018-12-05 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20181205_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 5, 15, 16, 14, 982880, tzinfo=utc)),
        ),
    ]
